name: Deploy ASP.NET Core App

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:
    inputs:
      Environment:
        description: "Choose the environment to deploy"
        required: true
        default: "test"
        type: choice
        options:
          - test
          - prod

jobs:
  deploy:
    runs-on: windows-latest
    env:
      ENVIRONMENT: ${{ inputs.Environment }}
      S3_BUCKET:  ${{ inputs.Environment }}-iis-app-deployment-s3
      ARTIFACT_PATH: ./publish/
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore

      - name: Publish app
        run: dotnet publish -c Release -o publish
      
      - name: Set upload folder path based on date (UTC)
        id: date
        run: echo "date_folder=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload published files to S3 (date folder, overwrite if re-run today)
        run: |
          aws s3 sync ${{ env.ARTIFACT_PATH }} s3://${{ env.S3_BUCKET }}/${{ steps.date.outputs.date_folder }}/ --delete
      
      # - name: Upload to S3
      #   uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --delete
      #   env:
      #     AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     SOURCE_DIR: "publish"
      #     DEST_DIR: "/webapp"

      # - name: Trigger Lambda
      #   run: |
      #     aws lambda invoke --function-name DeployWebAppFromS3 --region us-east-1 out.json